nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: ["http://localhost:4200"]
    allow_headers: ["Content-Type", "Authorization"]
    allow_methods: ["GET", "POST", "PUT", "DELETE"]
    expose_headers: ["Link"]
    max_age: 3600
